# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	    ${LAYERDIR}/recipes-*/*/*.bbappend \
	    ${LAYERDIR}/recipes-*/*.bb \
	    ${LAYERDIR}/recipes-*/*.bbappend"

BBFILE_COLLECTIONS += "rz-security"
BBFILE_PATTERN_rz-security := "^${LAYERDIR}/"

LAYERDEPENDS_rz-security = "rz-common"
LAYERSERIES_COMPAT_rz-security = "dunfell"

BBMASK_append_rzg2h = " firmware-pack "
BBMASK_append_rzg2l = " bptool-native "
