# For RZ/G2HMNE Security Features purpose

FILE_BOOTPRG_VERIFY_ENC_KEY = 'E-Key.bin'
FILE_BOOTPRG_VERIFY_SIG_KEY = 'SBS-Key.pem'
FILE_BOOT_KEYRING_ENC       = 'Keyring_Enc.bin'
FILE_PROVISIONING_KEY_ENC   = 'ProvisioningKey_Enc.bin'

TSIP_LIB_PATH_append_r8a774c0 = "${SYMLINK_NATIVE_SEC_LIB_DIR}/libr_secure_ip_lib_g2e.a.2.2.0"
TSIP_LIB_PATH_append_r8a774a1 = "${SYMLINK_NATIVE_SEC_LIB_DIR}/libr_secure_ip_lib_g2m.a.2.2.0"
TSIP_LIB_PATH_append_r8a774b1 = "${SYMLINK_NATIVE_SEC_LIB_DIR}/libr_secure_ip_lib_g2n.a.2.2.0"
TSIP_LIB_PATH_append_r8a774e1 = "${SYMLINK_NATIVE_SEC_LIB_DIR}/libr_secure_ip_lib_g2h.a.2.2.0"
